name: PHP CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-and-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: PHP lint
        run: |
          find app routes -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l
      # Optional but recommended: light static analysis to catch undefined functions
      - name: PHPStan (level 1 to start)
        run: |
          curl -sL https://github.com/phpstan/phpstan/releases/latest/download/phpstan.phar -o phpstan.phar
          php phpstan.phar analyse -c phpstan.neon.dist --no-progress --memory-limit=1G
